/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import Model.TaiKhoan;

/**
 * 
 * @author nguyenducnguyen
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    Color DefaultColor, ClickedColor;
    private TaiKhoan currentAcc;

    private Admin() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    public TaiKhoan getCurrentAcc() {
        return currentAcc;
    }


    public Admin(TaiKhoan t) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new FlatLightLaf());
        UIManager.put("Table.showVerticalLines", true);
        UIManager.put("Table.showHorizontalLines", true);
        initComponents();
        setLocationRelativeTo(null);
        this.currentAcc = t;
        KhachHangForm pf = new KhachHangForm();
        MainContent.add(pf).setVisible(true);
//        pf.checkRole(currentAcc);
        DefaultColor = new Color(255,51,51);
        ClickedColor = new Color(255,102,102);
        NavbarMenu.setBackground(DefaultColor);
        
        jPanelQuanLyKhachHang.setBackground(ClickedColor);
        jPanelTaoHoaDon.setBackground(DefaultColor);
        jPanelQuanLyHoaDon.setBackground(DefaultColor);  
        SanPham.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavbarMenu = new javax.swing.JPanel();
        SanPham = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NhapHang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PhieuNhap = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        XuatHang = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        DangXuat = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        NhaCungCap = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NameUser = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PhieuXuat = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TonKho = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TaiKhoan1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ThongKe = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Account = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanelTaoHoaDon = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelQuanLyHoaDon = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelQuanLyKhachHang = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        MainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình quản lý bán hàng - cửa hàng máy tính Nguyễn Khanh");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NavbarMenu.setBackground(new java.awt.Color(255, 51, 51));
        NavbarMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SanPham.setBackground(new java.awt.Color(255, 51, 51));
        SanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SanPhamMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SanPhamMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ SẢN PHẨM");

        javax.swing.GroupLayout SanPhamLayout = new javax.swing.GroupLayout(SanPham);
        SanPham.setLayout(SanPhamLayout);
        SanPhamLayout.setHorizontalGroup(
            SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SanPhamLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );
        SanPhamLayout.setVerticalGroup(
            SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SanPhamLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        NavbarMenu.add(SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 40));

        NhapHang.setBackground(new java.awt.Color(255, 51, 51));
        NhapHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhapHangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NhapHangMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QUẢN LÝ NHẬP HÀNG");

        javax.swing.GroupLayout NhapHangLayout = new javax.swing.GroupLayout(NhapHang);
        NhapHang.setLayout(NhapHangLayout);
        NhapHangLayout.setHorizontalGroup(
            NhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NhapHangLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );
        NhapHangLayout.setVerticalGroup(
            NhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhapHangLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        NavbarMenu.add(NhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 240, 30));

        PhieuNhap.setBackground(new java.awt.Color(255, 51, 51));
        PhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhieuNhapMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PhieuNhapMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QUẢN LÝ PHIẾU NHẬP");

        javax.swing.GroupLayout PhieuNhapLayout = new javax.swing.GroupLayout(PhieuNhap);
        PhieuNhap.setLayout(PhieuNhapLayout);
        PhieuNhapLayout.setHorizontalGroup(
            PhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuNhapLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        PhieuNhapLayout.setVerticalGroup(
            PhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhieuNhapLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        NavbarMenu.add(PhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 40));

        XuatHang.setBackground(new java.awt.Color(255, 51, 51));
        XuatHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XuatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XuatHangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                XuatHangMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("QUẢN LÝ XUẤT HÀNG");

        javax.swing.GroupLayout XuatHangLayout = new javax.swing.GroupLayout(XuatHang);
        XuatHang.setLayout(XuatHangLayout);
        XuatHangLayout.setHorizontalGroup(
            XuatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XuatHangLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        XuatHangLayout.setVerticalGroup(
            XuatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, XuatHangLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        NavbarMenu.add(XuatHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 40));

        DangXuat.setBackground(new java.awt.Color(255, 51, 51));
        DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuatMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DangXuatMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ĐĂNG XUẤT");

        javax.swing.GroupLayout DangXuatLayout = new javax.swing.GroupLayout(DangXuat);
        DangXuat.setLayout(DangXuatLayout);
        DangXuatLayout.setHorizontalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        DangXuatLayout.setVerticalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        NavbarMenu.add(DangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 240, -1));

        NhaCungCap.setBackground(new java.awt.Color(255, 51, 51));
        NhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhaCungCapMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NhaCungCapMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("QL NHÀ CUNG CẤP");

        javax.swing.GroupLayout NhaCungCapLayout = new javax.swing.GroupLayout(NhaCungCap);
        NhaCungCap.setLayout(NhaCungCapLayout);
        NhaCungCapLayout.setHorizontalGroup(
            NhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhaCungCapLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NhaCungCapLayout.setVerticalGroup(
            NhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NhaCungCapLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        NavbarMenu.add(NhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 40));

        NameUser.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser.setForeground(new java.awt.Color(255, 255, 255));
        NameUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser.setText("username");
        NameUser.setToolTipText("");
        NavbarMenu.add(NameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 12, 130, 20));

        jLabel8.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Xin chào!");
        NavbarMenu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        PhieuXuat.setBackground(new java.awt.Color(255, 51, 51));
        PhieuXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PhieuXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhieuXuatMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PhieuXuatMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("QUẢN LÝ PHIẾU XUẤT");

        javax.swing.GroupLayout PhieuXuatLayout = new javax.swing.GroupLayout(PhieuXuat);
        PhieuXuat.setLayout(PhieuXuatLayout);
        PhieuXuatLayout.setHorizontalGroup(
            PhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuXuatLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PhieuXuatLayout.setVerticalGroup(
            PhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhieuXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        NavbarMenu.add(PhieuXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 40));

        TonKho.setBackground(new java.awt.Color(255, 51, 51));
        TonKho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TonKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TonKhoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TonKhoMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("QUẢN LÝ TỒN KHO");

        javax.swing.GroupLayout TonKhoLayout = new javax.swing.GroupLayout(TonKho);
        TonKho.setLayout(TonKhoLayout);
        TonKhoLayout.setHorizontalGroup(
            TonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TonKhoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        TonKhoLayout.setVerticalGroup(
            TonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TonKhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        NavbarMenu.add(TonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 240, -1));

        TaiKhoan1.setBackground(new java.awt.Color(255, 51, 51));
        TaiKhoan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TaiKhoan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaiKhoan1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TaiKhoan1MousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("QUẢN LÝ TÀI KHOẢN");

        javax.swing.GroupLayout TaiKhoan1Layout = new javax.swing.GroupLayout(TaiKhoan1);
        TaiKhoan1.setLayout(TaiKhoan1Layout);
        TaiKhoan1Layout.setHorizontalGroup(
            TaiKhoan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoan1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        TaiKhoan1Layout.setVerticalGroup(
            TaiKhoan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        NavbarMenu.add(TaiKhoan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 240, -1));

        ThongKe.setBackground(new java.awt.Color(255, 51, 51));
        ThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongKeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ThongKeMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("THỐNG KÊ BÁO CÁO");

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        NavbarMenu.add(ThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 240, -1));

        Account.setBackground(new java.awt.Color(255, 51, 51));
        Account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AccountMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ĐỔI THÔNG TIN");

        javax.swing.GroupLayout AccountLayout = new javax.swing.GroupLayout(Account);
        Account.setLayout(AccountLayout);
        AccountLayout.setHorizontalGroup(
            AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        AccountLayout.setVerticalGroup(
            AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        NavbarMenu.add(Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 240, -1));

        jPanelTaoHoaDon.setBackground(new java.awt.Color(255, 51, 51));
        jPanelTaoHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTaoHoaDonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTaoHoaDonMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TẠO HOÁ ĐƠN");

        javax.swing.GroupLayout jPanelTaoHoaDonLayout = new javax.swing.GroupLayout(jPanelTaoHoaDon);
        jPanelTaoHoaDon.setLayout(jPanelTaoHoaDonLayout);
        jPanelTaoHoaDonLayout.setHorizontalGroup(
            jPanelTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTaoHoaDonLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanelTaoHoaDonLayout.setVerticalGroup(
            jPanelTaoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTaoHoaDonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        NavbarMenu.add(jPanelTaoHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 30));

        jPanelQuanLyHoaDon.setBackground(new java.awt.Color(255, 51, 51));
        jPanelQuanLyHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelQuanLyHoaDonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelQuanLyHoaDonMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("QUẢN LÝ HOÁ ĐƠN");

        javax.swing.GroupLayout jPanelQuanLyHoaDonLayout = new javax.swing.GroupLayout(jPanelQuanLyHoaDon);
        jPanelQuanLyHoaDon.setLayout(jPanelQuanLyHoaDonLayout);
        jPanelQuanLyHoaDonLayout.setHorizontalGroup(
            jPanelQuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyHoaDonLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanelQuanLyHoaDonLayout.setVerticalGroup(
            jPanelQuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        NavbarMenu.add(jPanelQuanLyHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 30));

        jPanelQuanLyKhachHang.setBackground(new java.awt.Color(255, 51, 51));
        jPanelQuanLyKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelQuanLyKhachHangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelQuanLyKhachHangMousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("QUẢN LÝ KH");

        javax.swing.GroupLayout jPanelQuanLyKhachHangLayout = new javax.swing.GroupLayout(jPanelQuanLyKhachHang);
        jPanelQuanLyKhachHang.setLayout(jPanelQuanLyKhachHangLayout);
        jPanelQuanLyKhachHangLayout.setHorizontalGroup(
            jPanelQuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQuanLyKhachHangLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanelQuanLyKhachHangLayout.setVerticalGroup(
            jPanelQuanLyKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyKhachHangLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        NavbarMenu.add(jPanelQuanLyKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 30));

        getContentPane().add(NavbarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 750));

        MainContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MainContentLayout = new javax.swing.GroupLayout(MainContent);
        MainContent.setLayout(MainContentLayout);
        MainContentLayout.setHorizontalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        MainContentLayout.setVerticalGroup(
            MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        getContentPane().add(MainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1180, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanPhamMousePressed
        // TODO add your handling code here:
        SanPham.setBackground(ClickedColor);
        jPanelQuanLyKhachHang.setBackground(DefaultColor);
        jPanelTaoHoaDon.setBackground(DefaultColor);
        jPanelQuanLyHoaDon.setBackground(DefaultColor);  
        PhieuNhap.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        MainContent.removeAll();
        SanPhamForm p = new SanPhamForm();
        MainContent.add(p).setVisible(true);
    }//GEN-LAST:event_SanPhamMousePressed

    private void NhaCungCapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhaCungCapMousePressed
        // TODO add your handling code here:
        NhaCungCap.setBackground(ClickedColor);
        jPanelTaoHoaDon.setBackground(DefaultColor);
        jPanelQuanLyHoaDon.setBackground(DefaultColor);  
        SanPham.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(DefaultColor);
        jPanelQuanLyKhachHang.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_NhaCungCapMousePressed

    private void NhapHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhapHangMousePressed
        // TODO add your handling code here:
        NhapHang.setBackground(ClickedColor);
        jPanelTaoHoaDon.setBackground(DefaultColor);
        jPanelQuanLyHoaDon.setBackground(DefaultColor);  
        SanPham.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        jPanelQuanLyKhachHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_NhapHangMousePressed

    private void PhieuNhapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhieuNhapMousePressed
        // TODO add your handling code here:
        PhieuNhap.setBackground(ClickedColor);
        jPanelTaoHoaDon.setBackground(DefaultColor);
        jPanelQuanLyHoaDon.setBackground(DefaultColor);  
        SanPham.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        jPanelQuanLyKhachHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_PhieuNhapMousePressed

    private void XuatHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XuatHangMousePressed
        // TODO add your handling code here:
        jPanelQuanLyKhachHang.setBackground(DefaultColor);
        jPanelTaoHoaDon.setBackground(DefaultColor);
        jPanelQuanLyHoaDon.setBackground(DefaultColor);  
        SanPham.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        XuatHang.setBackground(ClickedColor);
        PhieuXuat.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_XuatHangMousePressed

    private void PhieuXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhieuXuatMousePressed
        // TODO add your handling code here:
        jPanelQuanLyKhachHang.setBackground(DefaultColor);
        jPanelTaoHoaDon.setBackground(DefaultColor);
        jPanelQuanLyHoaDon.setBackground(DefaultColor);  
        SanPham.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(ClickedColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_PhieuXuatMousePressed

    private void SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanPhamMouseClicked
        // TODO add your handling code here:
        SanPhamForm ac = new SanPhamForm();
        MainContent.removeAll();
        MainContent.add(ac).setVisible(true);
    }//GEN-LAST:event_SanPhamMouseClicked

    private void TonKhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TonKhoMousePressed
        // TODO add your handling code here:
        jPanelQuanLyKhachHang.setBackground(DefaultColor);
        jPanelTaoHoaDon.setBackground(DefaultColor);
        jPanelQuanLyHoaDon.setBackground(DefaultColor);  
        SanPham.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(ClickedColor);
        TaiKhoan1.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_TonKhoMousePressed

    private void DangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DangXuatMousePressed

    private void NhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhaCungCapMouseClicked
        // TODO add your handling code here:
        NhaCungCapForm af = new NhaCungCapForm();
        MainContent.removeAll();
        MainContent.add(af).setVisible(true);
    }//GEN-LAST:event_NhaCungCapMouseClicked

    private void TonKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TonKhoMouseClicked
        // TODO add your handling code here:
        TonKhoForm px = new TonKhoForm();
        MainContent.removeAll();
        MainContent.add(px).setVisible(true);

    }//GEN-LAST:event_TonKhoMouseClicked

    private void NhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhapHangMouseClicked
        // TODO add your handling code here:
        NhapHangForm nhaphang = new NhapHangForm();
        nhaphang.setNguoiNhapHang(this.currentAcc.getUser());
        MainContent.removeAll();
        MainContent.add(nhaphang).setVisible(true);
    }//GEN-LAST:event_NhapHangMouseClicked

    private void PhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhieuNhapMouseClicked
        // TODO add your handling code here:
        PhieuNhapForm pn = new PhieuNhapForm(this.getCurrentAcc());
        MainContent.removeAll();
        MainContent.add(pn).setVisible(true);
    }//GEN-LAST:event_PhieuNhapMouseClicked

    private void XuatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XuatHangMouseClicked
        // TODO add your handling code here:
        XuatHangForm xh = new XuatHangForm();
        xh.setNguoiTao(this.currentAcc.getFullName());
        MainContent.removeAll();
        MainContent.add(xh).setVisible(true);
    }//GEN-LAST:event_XuatHangMouseClicked

    private void PhieuXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhieuXuatMouseClicked
        // TODO add your handling code here:
        PhieuXuatForm px = new PhieuXuatForm(this.getCurrentAcc());
        MainContent.removeAll();
        MainContent.add(px).setVisible(true);
    }//GEN-LAST:event_PhieuXuatMouseClicked

    private void DangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatMouseClicked
        // TODO add your handling code here:
        int relly = JOptionPane.showConfirmDialog(
                null,
                "Bạn muốn thoát khỏi chương trình ?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);
        if (relly == JOptionPane.YES_OPTION) {
            this.dispose();
            GiaoDienDangNhap a = new GiaoDienDangNhap();
            a.setVisible(true);
        } else {
            DangXuat.setBackground(DefaultColor);
        }
    }//GEN-LAST:event_DangXuatMouseClicked

    private void TaiKhoan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaiKhoan1MouseClicked
        // TODO add your handling code here:
        TaiKhoanForm ac = new TaiKhoanForm();
        MainContent.removeAll();
        MainContent.add(ac).setVisible(true);
    }//GEN-LAST:event_TaiKhoan1MouseClicked

    private void TaiKhoan1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaiKhoan1MousePressed
        // TODO add your handling code here:
        jPanelQuanLyKhachHang.setBackground(DefaultColor);
        jPanelTaoHoaDon.setBackground(DefaultColor);
        jPanelQuanLyHoaDon.setBackground(DefaultColor);  
        SanPham.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(ClickedColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_TaiKhoan1MousePressed

    private void ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMouseClicked
        // TODO add your handling code here:
        ThongKeForm tk = new ThongKeForm();
        MainContent.removeAll();
        MainContent.add(tk).setVisible(true);
    }//GEN-LAST:event_ThongKeMouseClicked

    private void ThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMousePressed
        // TODO add your handling code here:
        jPanelQuanLyKhachHang.setBackground(DefaultColor);
        jPanelTaoHoaDon.setBackground(DefaultColor);
        jPanelQuanLyHoaDon.setBackground(DefaultColor);  
        ThongKe.setBackground(ClickedColor);
        SanPham.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(DefaultColor);
    }//GEN-LAST:event_ThongKeMousePressed

    private void AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMouseClicked
        // TODO add your handling code here:
        ThayDoiMatKhau cp = new ThayDoiMatKhau(this, rootPaneCheckingEnabled, getCurrentAcc());
        cp.setVisible(true);
    }//GEN-LAST:event_AccountMouseClicked

    private void AccountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát ?", "Exit?", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jPanelTaoHoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTaoHoaDonMousePressed
        // TODO add your handling code here:
        jPanelQuanLyKhachHang.setBackground(DefaultColor);
        jPanelTaoHoaDon.setBackground(ClickedColor);
        jPanelQuanLyHoaDon.setBackground(DefaultColor);  
        SanPham.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_jPanelTaoHoaDonMousePressed

    private void jPanelQuanLyHoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQuanLyHoaDonMousePressed
        // TODO add your handling code here:
        jPanelQuanLyKhachHang.setBackground(DefaultColor);
        jPanelTaoHoaDon.setBackground(DefaultColor);
        jPanelQuanLyHoaDon.setBackground(ClickedColor);  
        SanPham.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
    }//GEN-LAST:event_jPanelQuanLyHoaDonMousePressed

    private void jPanelTaoHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTaoHoaDonMouseClicked
        // TODO add your handling code here:
        ThemHoaDonForm xh = new ThemHoaDonForm();
        xh.setNguoiTao(this.currentAcc.getFullName());
        MainContent.removeAll();
        MainContent.add(xh).setVisible(true);
    }//GEN-LAST:event_jPanelTaoHoaDonMouseClicked

    private void jPanelQuanLyKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQuanLyKhachHangMousePressed
        // TODO add your handling code here:
        jPanelQuanLyKhachHang.setBackground(ClickedColor);
        jPanelTaoHoaDon.setBackground(DefaultColor);
        jPanelQuanLyHoaDon.setBackground(DefaultColor);  
        SanPham.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(DefaultColor);
        ThongKe.setBackground(DefaultColor);
        MainContent.removeAll();
        KhachHangForm p = new KhachHangForm();
        MainContent.add(p).setVisible(true);
    }//GEN-LAST:event_jPanelQuanLyKhachHangMousePressed

    private void jPanelQuanLyKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQuanLyKhachHangMouseClicked
        // TODO add your handling code here:
        KhachHangForm ac = new KhachHangForm();
        MainContent.removeAll();
        MainContent.add(ac).setVisible(true);
    }//GEN-LAST:event_jPanelQuanLyKhachHangMouseClicked

    private void jPanelQuanLyHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQuanLyHoaDonMouseClicked
        // TODO add your handling code here:
        QuanLyHoaDonForm px = new QuanLyHoaDonForm(this.getCurrentAcc());
        MainContent.removeAll();
        MainContent.add(px).setVisible(true);

    }//GEN-LAST:event_jPanelQuanLyHoaDonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    public void setName(String name) {
        this.NameUser.setText(name);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Account;
    private javax.swing.JPanel DangXuat;
    private javax.swing.JPanel MainContent;
    private javax.swing.JLabel NameUser;
    private javax.swing.JPanel NavbarMenu;
    private javax.swing.JPanel NhaCungCap;
    private javax.swing.JPanel NhapHang;
    private javax.swing.JPanel PhieuNhap;
    private javax.swing.JPanel PhieuXuat;
    private javax.swing.JPanel SanPham;
    private javax.swing.JPanel TaiKhoan1;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JPanel TonKho;
    private javax.swing.JPanel XuatHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelQuanLyHoaDon;
    private javax.swing.JPanel jPanelQuanLyKhachHang;
    private javax.swing.JPanel jPanelTaoHoaDon;
    // End of variables declaration//GEN-END:variables
}
